# 11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [2]:
import numpy as np
x = np.array([73, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print(x,y)
print(np.greater(x,y))
print(np.greater_equal(x,y))

[  73   79   85   90  150 -135  120  -10   60  100] [  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
[ True False False False False False False False False False]
[ True  True  True  True  True  True  True  True  True False]


# 12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array. 

In [3]:
a=np.array([1,7,13,105])
print(a)
print("%d bytes" % (a.size*a.itemsize))

[  1   7  13 105]
16 bytes


In [4]:
print("%d bytes" % (a.itemsize))

4 bytes


In [5]:
print("%d bytes" % (a.size))

4 bytes


# 13. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [6]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
a=np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
a=np.ones(10)
a*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# 14. Write a NumPy program to create an array of the integers from 30 to70. 

In [9]:
a=np.arange(30,71)
a

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

# 15. Write a NumPy program to create an array of all the even integers from 30 to 70. 

In [10]:
a=np.arange(30,71,2)
a

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [19]:
a=np.arange(30,71,2)#another way to write
if (np.all(a%2))==0:
    print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


# 16. Write a NumPy program to create a 3x3 identity matrix.

In [27]:
a=np.random.randn(3,3)
a

array([[-0.37605485, -1.14650956, -0.00939758],
       [-1.08062772,  0.80582249, -0.37281474],
       [-1.12695886,  0.18538737,  1.61865276]])

In [33]:
a=np.identity(3)
a*3#another way to write

array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

# 17. Write a NumPy program to generate a random number between 0 and 1.

In [50]:
a=np.random.randn(10)
a

array([ 0.49449946,  0.42100342,  1.0866025 ,  0.36044071,  1.13163506,
       -0.08709225, -0.31400651,  1.34308703, -2.21834165,  0.05632176])

In [51]:
a=np.random.normal(0,1,1)
a#another way to write

array([-1.29824945])

# 18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution. 

In [52]:
a=np.random.normal(0,1,15)
a

array([ 2.07487625,  0.18093485, -0.17579036,  2.11937474, -1.56706979,
        0.71990932, -1.33368487, -0.23100709, -0.86187501, -2.65258044,
       -0.10753246, -0.55322611,  0.85941833, -0.67278798,  0.55665576])

# 19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [55]:
a=np.arange(16,55)
a

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

# 20. Write a NumPy program to create a 3X4 array using and iterate over it. 

In [66]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
for x in np.nditer(a):
    print(x,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 