# 21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50. 

In [2]:
import numpy as np
a=np.arange(5,50,10)
a

array([ 5, 15, 25, 35, 45])

In [3]:
a=np.linspace(5,50,10)
a#another way to write

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

# 22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [4]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
a[(a >= 9) & (a <= 15)]*=-1
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19])

# 23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10. 

In [21]:
x = np.random.randint(0, 11, 5)
print(x)

[10  8  9  4  4]


# 24. Write a NumPy program to multiply the values of two given vectors.

In [24]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=a*b
print(c)

[ 5 12 21 32]


# 25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21. 

In [26]:
a=np.arange(10,22).reshape(3,4)
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

# 26. Write a NumPy program to find the number of rows and columns of a given matrix. 

In [31]:
a=np.array([[1,2,3,4]])
a.shape

(1, 4)

In [32]:
a= np.arange(10,22).reshape((3, 4))
a.shape

(3, 4)

# 27. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.

In [34]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 28. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0. 

In [45]:
a=x = np.ones((10, 10))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# 29. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [48]:
a=np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# 30. Write a NumPy program to create an 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [55]:
x = np.zeros((4, 4))
x[::2, -1::-2] = 1
x[1::2, ::-2] = 1
print(x)

[[0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]]
