# 1.Write a NumPy program to get the numpy version and show numpy build configuration.

In [2]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.14.3
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/Anaconda3/python\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Users/hp/Anaconda3/python\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hp/Anaconda3/python\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\window

# 2. Write a NumPy program to  get help on the add function.

In [3]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

# 3. Write a NumPy program to test whether none of the elements of a given array is zero.

In [4]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
if np.all(a)==0:
    print('correct')
else:
    print('wrong')

correct


In [6]:
#an other to check the elements
x=[0,1,2,3,4]
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Test if none of the elements of the said array is zero:
False


# 4. Write a NumPy program to test if any of the elements of a given array is non-zero. 

In [7]:
a=np.random.randn(10)
a

array([-0.68374585,  0.82893993, -1.07587212,  0.30127195, -0.34160608,
       -0.14176276, -0.2217972 ,  0.10981711, -1.14342854, -0.1454992 ])

In [8]:
if np.all(a)==0:
    print('correct')
else:
    print('false')

false


In [9]:
#an other way to write
a=[0,1,2,3,4]
print(np.all(a))

False


# 5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number). 

In [10]:
a=np.random.randn(2,10)
a

array([[-1.76328917, -0.07041811,  0.58494761, -0.16661482, -1.53291312,
         0.41866513, -0.32668246, -2.41604144, -2.08014681, -1.18071884],
       [-0.01330531, -0.08793684, -0.87139835,  2.67946416, -0.61052466,
        -0.55394634, -1.452551  , -0.18458499,  0.65522452, -0.62852473]])

In [11]:
a=np.random.randn(2,10)
print(np.isfinite(a))

[[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


In [12]:
#another way to write
q=12
a=[1,2,3,np.nan,np.inf,q]
print(np.isfinite(a))

[ True  True  True False False  True]


# 6. Write a NumPy program to test element-wise for positive or negative infinity.

In [15]:
a=[1,2,3,np.nan,np.inf]
print(np.isinf(a))

[False False False False  True]


# 7. Write a NumPy program to test element-wise for NaN of a given array.

In [22]:
a=[1,2,3,np.nan,np.inf]
print(np.isnan(a))

[False False False  True False]


# 8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test if a given number is a scalar type or not. 

In [24]:
a=np.random.randn(2,5)
a

array([[-1.16961759,  0.4930527 , -0.01431958, -2.44253158,  0.99691851],
       [ 1.4911673 , -0.37315312, -1.03202908, -0.59516387, -1.50279794]])

In [25]:
print(np.iscomplex(a))

[[False False False False False]
 [False False False False False]]


In [26]:
print(np.isreal(a))

[[ True  True  True  True  True]
 [ True  True  True  True  True]]


In [27]:
print(np.isscalar(a))

False


In [35]:
a=([-2])#scalar list ko accept nai karta
print(np.isscalar(a))

False


In [38]:
a=(1.2)
b=(-1)
c=(1)
print(np.isscalar(a))
print(np.isscalar(b))
print(np.isscalar(c))

True
True
True


In [47]:
a=np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
a

array([1. +1.j, 1. +0.j, 4.5+0.j, 3. +0.j, 2. +0.j, 0. +2.j])

In [49]:
print(np.iscomplex(a))

[ True False False False False  True]


# 9. Write a NumPy program to test if two arrays are element-wise equal within a tolerance.

In [60]:
print(np.allclose([1,2,3],[12,1,3]))

False


In [61]:
print(np.allclose([1,2,3],[1,2,3]))

True


# 10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [66]:
x = np.array([3, 5])
y = np.array([2, 5])
print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less_equal(x,y))
print(np.less(x,y))

[ True False]
[ True  True]
[False  True]
[False False]
